#!/usr/bin/env python3
import socket, threading
import random

class ClientThread(threading.Thread):

    def __init__(self,clientAddress,clientsocket,clients,cid):#,to):   ):
        threading.Thread.__init__(self)
        #self.to=to# MAYBE SOURCE OR SOMEONE ELSE
        self.cid=cid# USER
        self.csocket = clientsocket
        self.clients=clients
        print ("New connection added: ", clientAddress)


    def run(self):
        print ("Connection from : ", clientAddress)
        #self.csocket.send(bytes("Hi, This is from Server..",'utf-8'))

        msg = ''
        divide=":|:"
        i=0
        to='000000'
        print("[+]Starting Recieve client CID:",self.cid)
        isCD=0

        while True:
            rawdata = self.csocket.recv(2048)
            data = rawdata.decode().split(divider,4)
            print ("from client",rawdata)
            #add here no data if
            if rawdata=="":
                i+=1
                print('retrying ',i)
                if i>60:
                    break
            #elif not(len(data)>3):
                #print('packet Corrupted')
            elif(data[0]=="000000" and data[2]=='SINK'): #fix these if statements
                print("[+]Client acting as Sink")
                to='000000'
                self.csocket.sendall(bytes(self.cid+divider+to+divider+"CACK"+divider+data[2],'UTF-8'))
            elif(data[0]=="000000" and data[2]=='SORC'):
                print("[+]",self.cid," acting as source for :",data[3])
                if(data[3] in self.clients):
                    sendsocket=self.clients[data[3]]
                    print("[+]Client ",data[3]," found")#now as send a signal to data to change to [CSRC]
                    sendsocket.sendall(bytes(data[3]+divider+self.cid+divider+"CSRC"+divider+self.cid,'UTF-8'))
                    k = self.csocket.recv(2048)#self.scoket
                    dataack = k.decode().split(divider,4)
                    print('dataack')
                    if(dataack[2]=='CACK'):
                        isCD=1
                        to=data[3]
                        print('[+]connected to device ',data[3])
                        sendsocket=self.clients[data[0]]
                        #self.socket.sendall(bytes(self.cid+divider+'000000'+divider+"CACK"+divider+'SORC'+divider+to,'UTF-8'))
                    elif dataack[2]=='NACK':
                        isCD=0
                        to='000000'
                        #self.socket.sendall(bytes(self.cid+divider+'000000'+divider+"FCN"+divider+'SORC'+divider+to,'UTF-8'))
                        print('[-]connection to device ',data[3],' failed')
                    else:
                        print('dataack data was',k.decode())
                else:
                    print("[-]Client ",data[3]," not found")
                    self.csocket.sendall(bytes(self.cid+divider+to+divider+"FCN"+divider+data[2]+divider+data[3],'UTF-8'))
            elif data[2]=='CLOSE':
                print('[-]Disconnecting from user Initiated by Client')
                break

            if data[2]=="CHAT" or data[2]=='NULL' or data[2]=='CACK' or data[2]=='NACK':
                    print('Chat Data is ',data[3],' data[0] is',data[0],'and to is ',to)
            #Efor x in rawdata.decode():
                    #print(x)
                    if data[2]=='CACK' or data[2] =='NACK':
                        print(data[2],'|',self.cid,'[',data[1],']', '->',data[0])
                        self.clients[data[0]].sendall(bytes(data[0]+divider+self.cid+divider+data[2]+divider,'UTF-8'))

                    if data[0]=='000000':
                        print(self.cid,'->',self.cid,' to =',to)
                        self.csocket.sendall(bytes(self.cid+divider+to+divider+"CHAT"+divider+data[3],'UTF-8'))
                    else:
                        print(self.cid,'->',data[0],' to =',to)
                        self.clients[data[0]].sendall(bytes(data[0]+divider+self.cid+divider+"CHAT"+divider+data[3],'UTF-8'))
                    i=0
        print("Client at ", clientAddress , " disconnected...")
        del self.clients[self.cid]




#DRIVER CODE
LOCALHOST = "127.0.0.1"
PORT = 8080
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server.bind((LOCALHOST, PORT))
client={}
print("Server started")
print("Waiting for client request..")

while True:
    print("[+]Accepting clients")
    server.listen(1)
    clientsock, clientAddress = server.accept()

    divider=":|:"
    clientid=''
    session=''
    for x in range(6):
    	clientid+=str(random.randint(1,9))
    #newthread = ClientThread(clientAddress, clientsock,client,clientid)
    session+=clientid+divider+'000000'+divider+"CID"+divider+clientid+divider
    client[clientid]=clientsock
    print("[+]Client added ")
    print(client)
#data form at_kkmodi
    newthread = ClientThread(clientAddress, clientsock,client,clientid)
    # remove this above one
    newthread.start()





'''
if client wants to connect to other client then send clientid
server id 00000
 wants to connect SORC
doesn't want to connect SINK
client.sendall(bytes('SERVER'+divider+clientid+divider+11+divider+_THECLIENTIDHERE_,'UTF-8'))
 MESSAGE FORMAT   TO/from/what/data
 NACK no ack
CACK =change ack
FCN= failed change negative ack
CSRC changing source
'''
